In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../data/raw/Testlio - AI_ML dataset.csv")

In [7]:
pd.DataFrame(data['product_name'].value_counts()).head(20)

             product_name
product_117          1311
product_173           982
product_10            548
product_20            530
product_17            470
product_69            437
product_52            311
product_110           295
product_115           274
product_113           251
product_31            188
product_116           164
product_167           143
product_70            142
product_91            138
product_146           138
product_164           130
product_121           130
product_49            115
product_78            108